/**
 * Assemble the packaged skill tree.
 *
 * The committed skill lives at `.agents/skills/fluentui/` and is regenerated by
 * the skill generator. The published package must contain a plain `skills/`
 * directory instead, so this step copies the committed tree to
 * `skills/fluentui/`. It always replaces the destination, which keeps the
 * packaged copy an exact match of the committed one.
 *
 * Both directories are derived from the project root; the step accepts no
 * destination override, so it can only ever replace the packaged skill
 * directory inside the repository.
 *
 * @module scripts/skill/assemble
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** The committed skill directory, relative to the project root. */
export const SOURCE_DIR = path.join('.agents', 'skills', 'fluentui');

/** The packaged skill directory, relative to the project root. */
export const DEST_DIR = path.join('skills', 'fluentui');

/**
 * The outcome of an assemble run.
 */
export interface AssembleResult {
  /** Absolute source directory. */
  sourceDir: string;
  /** Absolute destination directory. */
  destDir: string;
  /** Number of files copied. */
  files: number;
}

/**
 * Counts the regular files below a directory, recursively.
 *
 * @param dir - Directory to walk.
 * @returns The number of files found.
 */
function countFiles(dir: string): number {
  let total = 0;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      total += countFiles(fullPath);
    } else if (entry.isFile()) {
      total += 1;
    }
  }

  return total;
}

/**
 * Copies the committed skill tree into the packaged location.
 *
 * @param cwd - Project root directory.
 * @returns The resolved directories and the file count.
 * @throws When the source does not contain a `SKILL.md`.
 */
export function assembleSkill(cwd: string = process.cwd()): AssembleResult {
  const sourceDir = path.resolve(cwd, SOURCE_DIR);
  const destDir = path.resolve(cwd, DEST_DIR);

  if (!fs.existsSync(path.join(sourceDir, 'SKILL.md'))) {
    throw new Error(`skill source is missing SKILL.md: ${sourceDir}`);
  }

  fs.rmSync(destDir, { recursive: true, force: true });
  fs.mkdirSync(path.dirname(destDir), { recursive: true });
  fs.cpSync(sourceDir, destDir, { recursive: true });

  return { sourceDir, destDir, files: countFiles(destDir) };
}

/**
 * Runs the assemble CLI.
 *
 * @param cwd - Project root.
 * @returns Process exit code.
 */
export function runAssemble(cwd: string = process.cwd()): number {
  try {
    const result = assembleSkill(cwd);
    process.stdout.write(`Assembled ${result.files} file(s) into ${result.destDir}\n`);
    return 0;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`${message}\n`);
    return 1;
  }
}

// Allow `node --import tsx scripts/skill/assemble.ts` to run the CLI.
const invokedDirectly =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  process.exitCode = runAssemble();
}
