/**
 * Assemble the packaged skill tree.
 *
 * The committed skill lives at `.agents/skills/fluentui/` and is regenerated by
 * the skill generator. The published package must contain a plain `skills/`
 * directory instead, so this step copies the committed tree to
 * `skills/fluentui/`. It always replaces the destination, which keeps the
 * packaged copy an exact match of the committed one.
 *
 * @module scripts/skill/assemble
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** The committed skill directory, relative to the project root. */
export const DEFAULT_SOURCE_DIR = path.join('.agents', 'skills', 'fluentui');

/** The packaged skill directory, relative to the project root. */
export const DEFAULT_DEST_DIR = path.join('skills', 'fluentui');

/**
 * Options for an assemble run.
 */
export interface AssembleOptions {
  /** Project root directory. */
  cwd?: string;
  /** Source skill directory, absolute or relative to `cwd`. */
  sourceDir?: string;
  /** Destination skill directory, absolute or relative to `cwd`. */
  destDir?: string;
}

/**
 * The outcome of an assemble run.
 */
export interface AssembleResult {
  /** Absolute source directory. */
  sourceDir: string;
  /** Absolute destination directory. */
  destDir: string;
  /** Number of files copied. */
  files: number;
}

/**
 * Counts the regular files below a directory, recursively.
 *
 * @param dir - Directory to walk.
 * @returns The number of files found.
 */
function countFiles(dir: string): number {
  let total = 0;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      total += countFiles(fullPath);
    } else if (entry.isFile()) {
      total += 1;
    }
  }

  return total;
}

/**
 * Copies the committed skill tree into the packaged location.
 *
 * @param options - Assemble inputs.
 * @returns The resolved directories and the file count.
 * @throws When the source does not contain a `SKILL.md`.
 */
export function assembleSkill(options: AssembleOptions = {}): AssembleResult {
  const cwd = options.cwd ?? process.cwd();
  const sourceDir = path.resolve(cwd, options.sourceDir ?? DEFAULT_SOURCE_DIR);
  const destDir = path.resolve(cwd, options.destDir ?? DEFAULT_DEST_DIR);

  if (!fs.existsSync(path.join(sourceDir, 'SKILL.md'))) {
    throw new Error(`skill source is missing SKILL.md: ${sourceDir}`);
  }

  fs.rmSync(destDir, { recursive: true, force: true });
  fs.mkdirSync(path.dirname(destDir), { recursive: true });
  fs.cpSync(sourceDir, destDir, { recursive: true });

  return { sourceDir, destDir, files: countFiles(destDir) };
}

/**
 * Runs the assemble CLI.
 *
 * @param argv - Command-line arguments (currently unused).
 * @param cwd - Project root.
 * @returns Process exit code.
 */
export function runAssemble(argv: string[] = [], cwd: string = process.cwd()): number {
  let sourceDir: string | undefined;
  let destDir: string | undefined;

  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--source') {
      sourceDir = argv[++i] ?? sourceDir;
    } else if (argv[i] === '--dest') {
      destDir = argv[++i] ?? destDir;
    }
  }

  try {
    const result = assembleSkill({ cwd, sourceDir, destDir });
    process.stdout.write(`Assembled ${result.files} file(s) into ${result.destDir}\n`);
    return 0;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`${message}\n`);
    return 1;
  }
}

// Allow `node --import tsx scripts/skill/assemble.ts` to run the CLI.
const invokedDirectly =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  process.exitCode = runAssemble(process.argv.slice(2));
}
