/**
 * The explicit source→destination mapping for the generated skill tree.
 *
 * One enhanced schema becomes a set of {@link SkillFile} objects held entirely
 * in memory. The writer never touches the filesystem until every id has passed
 * the safety checks, so an unsafe or malformed schema cannot leave a partial
 * tree behind.
 *
 * The mapping is deliberately a plain table of rules rather than a generic
 * templating system: each schema section has exactly one destination folder,
 * and the file name is the entity's own id. That keeps the output diffable and
 * makes the drift gate a byte comparison.
 *
 * Destination layout (relative to the skill root):
 * `references/{index.md, foundation/<id>.md, components/<id>.md,
 * categories/<category>.md, recipes/<group>/<id>.md, quick-reference/<id>.md}`.
 *
 * @module skill/mapping
 */

import type {
  CategoryGuidanceEntry,
  ComponentEntry,
  FluentUISchema,
  GuideEntry,
  RecipeEntry,
} from '../../src/types/schema.js';
import { renderPropsReference } from './render/props.js';
import { renderExamplesSection } from './render/stories.js';
import {
  appendMarker,
  bulletList,
  bulletSection,
  escapeTableCell,
  fencedCode,
  heading,
  inlineCode,
  joinSections,
  proseSection,
  table,
} from './render/sections.js';

/** The skill name; it is also the directory name under `.agents/skills/`. */
export const SKILL_NAME = 'fluentui';

/** Marker appended to every generated file so hand-written files stand out. */
export const GENERATED_MARKER =
  '<!-- Generated by scripts/skill/generate.ts — do not edit by hand. -->';

/** Folder, relative to the skill root, that holds all generated references. */
export const REFERENCE_DIR = 'references';

/**
 * Fixed order of recipe groups.
 *
 * Recipe files live under `references/recipes/<group>/`, and grouping them in
 * this order keeps the tree stable even when recipes are added or removed.
 */
export const RECIPE_GROUP_ORDER = [
  'forms',
  'data',
  'navigation',
  'modals',
  'layout',
  'state',
  'accessibility',
] as const;

/** A single generated file, with a POSIX-style path relative to the skill root. */
export interface SkillFile {
  /** Relative destination path, for example `references/components/button.md`. */
  path: string;

  /** Complete UTF-8 file content, ending with the generated marker. */
  content: string;
}

/**
 * Safe id pattern: lowercase kebab-case.
 *
 * Ids become file and directory names, so the pattern permits only `a-z`, `0-9`,
 * and single hyphens. It cannot express `..`, `/`, or a drive/absolute prefix,
 * which closes the path-traversal risk at the source.
 */
const SAFE_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * True when an id is safe to use as a single path component.
 *
 * @param id - Candidate id.
 * @returns True for a non-empty lowercase kebab-case id.
 */
export function isSafeSkillId(id: string): boolean {
  return typeof id === 'string' && SAFE_ID_PATTERN.test(id);
}

/** Throw a descriptive error when an id is not path-safe. */
function assertSafeId(kind: string, id: string): void {
  if (!isSafeSkillId(id)) {
    throw new Error(
      `Unsafe ${kind} id "${id}": ids must be lowercase kebab-case and may not contain "/" or "..".`,
    );
  }
}

/** Normalize line endings and append the generated marker. */
function finalize(markdown: string): string {
  const normalized = markdown.replace(/\r\n?/g, '\n').trimEnd();
  return appendMarker(normalized, GENERATED_MARKER);
}

// ============================================================================
// Entity renderers
// ============================================================================

/**
 * Render the identity header of a component file: name, package, import,
 * category, stability, and a deprecation warning when applicable.
 */
function renderComponentHeader(component: ComponentEntry): string {
  const lines = [heading(1, component.name), ''];
  if (component.deprecated) {
    const message = component.deprecationMessage
      ? `: ${component.deprecationMessage}`
      : '';
    lines.push(`> ⚠️ **Deprecated**${message}`, '>');
  }
  const version = component.packageVersion ? ` v${component.packageVersion}` : '';
  lines.push(
    `> **Package**: \`${component.packageName}\`${version}`,
    `> **Import**: \`${component.importStatement}\``,
    `> **Category**: ${component.category}`,
    `> **Stability**: ${component.stability}`,
  );
  return lines.join('\n');
}

/** Render the overview prose, falling back to a neutral line for raw entries. */
function renderComponentOverview(component: ComponentEntry): string {
  const description = component.enhanced?.description?.trim();
  const whenToUse = component.enhanced?.whenToUse?.trim();
  const body =
    description && description !== ''
      ? description
      : `${component.name} is part of the \`${component.packageName}\` package.`;
  return joinSections([
    heading(2, 'Overview'),
    body,
    whenToUse ? `**When to use**: ${whenToUse}` : '',
  ]);
}

/** Render the Do's and Don'ts section from enhanced content. */
function renderBestPractices(component: ComponentEntry): string {
  const best = component.enhanced?.bestPractices;
  if (!best || (best.dos.length === 0 && best.donts.length === 0)) {
    return '';
  }
  return joinSections([
    heading(2, 'Best Practices'),
    best.dos.length > 0 ? joinSections([heading(3, "Do's"), bulletList(best.dos)]) : '',
    best.donts.length > 0 ? joinSections([heading(3, "Don'ts"), bulletList(best.donts)]) : '',
  ]);
}

/** Render anti-patterns: each mistake paired with its correct approach. */
function renderAntiPatterns(component: ComponentEntry): string {
  const items = component.enhanced?.antiPatterns;
  if (!items || items.length === 0) {
    return '';
  }
  const blocks = items.map((item) =>
    joinSections([
      heading(3, item.title),
      `❌ ${item.problem}`,
      `✅ ${item.solution}`,
    ]),
  );
  return joinSections([heading(2, 'Anti-Patterns'), ...blocks]);
}

/** Render accessibility guidance: requirements, keyboard table, ARIA, screen reader. */
function renderAccessibility(component: ComponentEntry): string {
  const a11y = component.enhanced?.accessibility;
  if (!a11y) {
    return '';
  }
  const keyboard =
    a11y.keyboardSupport.length > 0
      ? table(
          ['Key', 'Action'],
          a11y.keyboardSupport.map((entry) => [
            inlineCode(entry.key),
            escapeTableCell(entry.action),
          ]),
        )
      : '';
  return joinSections([
    heading(2, 'Accessibility'),
    a11y.requirements ? `**Requirements**: ${a11y.requirements.trim()}` : '',
    keyboard,
    a11y.ariaAttributes.length > 0
      ? `**ARIA**: ${a11y.ariaAttributes.join(', ')}`
      : '',
    a11y.screenReaderBehavior
      ? `**Screen Reader**: ${a11y.screenReaderBehavior.trim()}`
      : '',
  ]);
}

/** Render the links footer: the component's category and related recipes. */
function renderComponentLinks(
  component: ComponentEntry,
  categoryIds: ReadonlySet<string>,
  recipeGroups: ReadonlyMap<string, string>,
): string {
  const links: string[] = [];
  if (categoryIds.has(component.category)) {
    links.push(
      `- [${component.category} category](../categories/${component.category}.md)`,
    );
  }
  for (const recipeId of component.enhanced?.relatedRecipes ?? []) {
    const group = recipeGroups.get(recipeId);
    if (group) {
      links.push(`- [${recipeId} recipe](../recipes/${group}/${recipeId}.md)`);
    }
  }
  if (component.relatedComponents.length > 0) {
    links.push(...component.relatedComponents.map((name) => `- ${name}`));
  }
  if (links.length === 0) {
    return '';
  }
  return joinSections([heading(2, 'See Also'), bulletList(links)]);
}

/**
 * Render one component reference file from its scraped data and prose.
 *
 * Examples come only from story code; every other section is additive and is
 * omitted when its source field is missing.
 */
function renderComponentFile(
  component: ComponentEntry,
  categoryIds: ReadonlySet<string>,
  recipeGroups: ReadonlyMap<string, string>,
): string {
  return finalize(
    joinSections([
      renderComponentHeader(component),
      renderComponentOverview(component),
      renderPropsReference(component),
      renderExamplesSection(component),
      renderBestPractices(component),
      renderAntiPatterns(component),
      renderAccessibility(component),
      proseSection('Styling', component.enhanced?.stylingTips),
      proseSection('Performance', component.enhanced?.performanceNotes),
      proseSection('Theming & Tokens', component.enhanced?.themingNotes),
      proseSection('Migration Notes', component.enhanced?.migrationNotes),
      bulletSection('Edge Cases', component.enhanced?.edgeCases),
      renderComponentLinks(component, categoryIds, recipeGroups),
    ]),
  );
}

/** Render a foundation or quick-reference guide file. */
function renderGuideFile(guide: GuideEntry): string {
  const examples = guide.codeExamples
    .map((example) =>
      joinSections([
        heading(3, example.title),
        example.description?.trim() ?? '',
        fencedCode(example.code, example.language || 'tsx'),
      ]),
    )
    .filter((block) => block !== '');
  return finalize(
    joinSections([
      heading(1, guide.title),
      guide.category ? `> **Category**: ${guide.category}` : '',
      guide.content?.trim() ?? '',
      bulletSection('Key Takeaways', guide.keyTakeaways),
      examples.length > 0
        ? joinSections([heading(2, 'Examples'), ...examples])
        : '',
      bulletSection('Pitfalls', guide.pitfalls),
      proseSection('Accessibility', guide.accessibilityNotes),
      guide.referencedComponents.length > 0
        ? `**Referenced components**: ${guide.referencedComponents.join(', ')}`
        : '',
    ]),
  );
}

/** Render a category guidance file, including links to its components. */
function renderCategoryFile(
  category: CategoryGuidanceEntry,
  components: ReadonlyMap<string, ComponentEntry>,
): string {
  const componentLinks = category.componentIds
    .filter((id) => components.has(id))
    .map((id) => `- [${components.get(id)?.name ?? id}](../components/${id}.md)`);
  return finalize(
    joinSections([
      heading(1, `${category.category} components`),
      heading(2, 'Overview'),
      category.overview,
      proseSection('When to Use', category.whenToUse),
      renderCategoryBestPractices(category),
      renderCategoryAntiPatterns(category),
      proseSection('Accessibility', category.accessibility),
      componentLinks.length > 0
        ? joinSections([
            heading(2, 'Components in this category'),
            bulletList(componentLinks),
          ])
        : '',
    ]),
  );
}

/** Render a category's shared Do's and Don'ts. */
function renderCategoryBestPractices(category: CategoryGuidanceEntry): string {
  const { dos, donts } = category.bestPractices;
  if (dos.length === 0 && donts.length === 0) {
    return '';
  }
  return joinSections([
    heading(2, 'Best Practices'),
    dos.length > 0 ? joinSections([heading(3, "Do's"), bulletList(dos)]) : '',
    donts.length > 0 ? joinSections([heading(3, "Don'ts"), bulletList(donts)]) : '',
  ]);
}

/** Render a category's shared anti-patterns. */
function renderCategoryAntiPatterns(category: CategoryGuidanceEntry): string {
  if (category.antiPatterns.length === 0) {
    return '';
  }
  const blocks = category.antiPatterns.map((item) =>
    joinSections([
      heading(3, item.title),
      `❌ ${item.problem}`,
      `✅ ${item.solution}`,
    ]),
  );
  return joinSections([heading(2, 'Anti-Patterns'), ...blocks]);
}

/** Render a recipe file from its prose, examples, and cross-links. */
function renderRecipeFile(
  recipe: RecipeEntry,
  components: ReadonlyMap<string, ComponentEntry>,
): string {
  // `components` is keyed by lowercased component name; recipes reference
  // components by display name rather than by id.
  const examples = recipe.examples
    .map((example) =>
      joinSections([
        heading(3, example.name),
        example.description?.trim() ?? '',
        fencedCode(example.code, example.language || 'tsx'),
      ]),
    )
    .filter((block) => block !== '');
  const componentLinks = recipe.referencedComponents
    .map((name) => components.get(name.trim().toLowerCase()))
    .filter((component): component is ComponentEntry => component !== undefined)
    .map((component) => `- [${component.name}](../../components/${component.id}.md)`);
  return finalize(
    joinSections([
      heading(1, recipe.title),
      `> **Group**: ${recipe.group}`,
      proseSection('Goal', recipe.goal),
      proseSection('When to Use', recipe.whenToUse),
      proseSection('When Not to Use', recipe.whenNotToUse),
      recipe.content?.trim() ?? '',
      examples.length > 0
        ? joinSections([heading(2, 'Examples'), ...examples])
        : '',
      bulletSection('Pitfalls', recipe.pitfalls),
      proseSection('Accessibility', recipe.accessibilityNotes),
      componentLinks.length > 0
        ? joinSections([
            heading(2, 'Components used'),
            bulletList(componentLinks),
          ])
        : '',
    ]),
  );
}

/** Render the routing index: task→recipe map, category index, and all references. */
function renderIndexFile(
  schema: FluentUISchema,
  orderedRecipes: readonly RecipeEntry[],
  orderedComponents: readonly ComponentEntry[],
): string {
  const taskTable = table(
    ['Task', 'Recipe', 'Group'],
    orderedRecipes.map((recipe) => [
      escapeTableCell(recipe.title),
      `[${recipe.id}](recipes/${recipe.group}/${recipe.id}.md)`,
      escapeTableCell(recipe.group),
    ]),
  );

  const categoryTable = table(
    ['Category', 'Components'],
    schema.categoryGuidance.map((category) => [
      `[${category.category}](categories/${category.id}.md)`,
      String(category.componentIds.length),
    ]),
  );

  return finalize(
    joinSections([
      heading(1, 'FluentUI reference index'),
      'Hand-written routing lives in `SKILL.md`; this file indexes every generated reference.',
      heading(2, 'Task → recipe'),
      taskTable,
      heading(2, 'Categories'),
      categoryTable,
      heading(2, 'Foundation'),
      bulletList(
        schema.foundation.map(
          (guide) => `[${guide.title}](foundation/${guide.id}.md)`,
        ),
      ),
      heading(2, 'Components'),
      bulletList(
        orderedComponents.map(
          (component) => `[${component.name}](components/${component.id}.md)`,
        ),
      ),
      heading(2, 'Quick reference'),
      bulletList(
        schema.quickReference.map(
          (guide) => `[${guide.title}](quick-reference/${guide.id}.md)`,
        ),
      ),
    ]),
  );
}

// ============================================================================
// Mapping entry point
// ============================================================================

/** Compare two objects by their `id` field for deterministic ordering. */
function byId(a: { id: string }, b: { id: string }): number {
  return a.id.localeCompare(b.id);
}

/**
 * Turn an enhanced schema into the complete set of skill files.
 *
 * The function validates every id and recipe group first, then renders all
 * files in memory and returns them sorted by path. It never writes to disk; a
 * thrown error therefore guarantees that no partial tree can appear.
 *
 * @param schema - The enhanced schema to render.
 * @returns Every generated file, sorted by relative path.
 * @throws When an id is unsafe, a recipe group is unknown, or a required
 *   collection is missing.
 */
export function buildSkillFiles(schema: FluentUISchema): SkillFile[] {
  const components = [...(schema.components ?? [])].sort(byId);
  const foundation = [...(schema.foundation ?? [])].sort(byId);
  const categories = [...(schema.categoryGuidance ?? [])].sort(byId);
  const quickReference = [...(schema.quickReference ?? [])].sort(byId);
  const recipes = [...(schema.recipes ?? [])];

  for (const component of components) {
    assertSafeId('component', component.id);
    assertSafeId('category', component.category);
  }
  for (const guide of [...foundation, ...quickReference]) {
    assertSafeId('guide', guide.id);
  }
  for (const category of categories) {
    assertSafeId('category', category.id);
  }
  for (const recipe of recipes) {
    assertSafeId('recipe', recipe.id);
    if (!RECIPE_GROUP_ORDER.includes(recipe.group as (typeof RECIPE_GROUP_ORDER)[number])) {
      throw new Error(
        `Unknown recipe group "${recipe.group}" for recipe "${recipe.id}". Allowed groups: ${RECIPE_GROUP_ORDER.join(', ')}.`,
      );
    }
  }

  const orderedRecipes = [...recipes].sort(
    (a, b) =>
      RECIPE_GROUP_ORDER.indexOf(a.group as (typeof RECIPE_GROUP_ORDER)[number]) -
        RECIPE_GROUP_ORDER.indexOf(b.group as (typeof RECIPE_GROUP_ORDER)[number]) ||
      a.id.localeCompare(b.id),
  );

  const componentById = new Map(components.map((c) => [c.id, c]));
  const componentByName = new Map(
    components.map((c) => [c.name.toLowerCase(), c]),
  );
  const categoryIds = new Set(categories.map((c) => c.id));
  const recipeGroups = new Map(recipes.map((r) => [r.id, r.group]));

  const files: SkillFile[] = [
    {
      path: `${REFERENCE_DIR}/index.md`,
      content: renderIndexFile(schema, orderedRecipes, components),
    },
    ...foundation.map((guide) => ({
      path: `${REFERENCE_DIR}/foundation/${guide.id}.md`,
      content: renderGuideFile(guide),
    })),
    ...components.map((component) => ({
      path: `${REFERENCE_DIR}/components/${component.id}.md`,
      content: renderComponentFile(component, categoryIds, recipeGroups),
    })),
    ...categories.map((category) => ({
      path: `${REFERENCE_DIR}/categories/${category.id}.md`,
      content: renderCategoryFile(category, componentById),
    })),
    ...orderedRecipes.map((recipe) => ({
      path: `${REFERENCE_DIR}/recipes/${recipe.group}/${recipe.id}.md`,
      content: renderRecipeFile(recipe, componentByName),
    })),
    ...quickReference.map((guide) => ({
      path: `${REFERENCE_DIR}/quick-reference/${guide.id}.md`,
      content: renderGuideFile(guide),
    })),
  ];

  return files.sort((a, b) => a.path.localeCompare(b.path));
}
