/**
 * The explicit source→destination mapping for the generated skill tree.
 *
 * One enhanced schema becomes a set of {@link SkillFile} objects held entirely
 * in memory. The writer never touches the filesystem until every id has passed
 * the safety checks, so an unsafe or malformed schema cannot leave a partial
 * tree behind.
 *
 * The mapping is deliberately a plain table of rules rather than a generic
 * templating system: each schema section has exactly one destination folder,
 * and the file name is the entity's own id. That keeps the output diffable and
 * makes the drift gate a byte comparison.
 *
 * Destination layout (relative to the skill root):
 * `references/{index.md, foundation/<id>.md, components/<id>.md,
 * categories/<category>.md, recipes/<group>/<id>.md, quick-reference/<id>.md}`.
 *
 * @module skill/mapping
 */

import type {
  CategoryGuidanceEntry,
  ComponentEntry,
  FluentUISchema,
  GuideEntry,
  RecipeEntry,
} from '../../src/types/schema.js';
import { renderPropsReference } from './render/props.js';
import { renderExamplesSection } from './render/stories.js';
import {
  appendMarker,
  bulletList,
  bulletSection,
  escapeLinkLabel,
  escapeTableCell,
  fencedCode,
  heading,
  inlineCode,
  joinSections,
  proseSection,
  table,
} from './render/sections.js';

/** The skill name; it is also the directory name under `.agents/skills/`. */
export const SKILL_NAME = 'fluentui';

/** Marker appended to every generated file so hand-written files stand out. */
export const GENERATED_MARKER =
  '<!-- Generated by scripts/skill/generate.ts — do not edit by hand. -->';

/** Folder, relative to the skill root, that holds all generated references. */
export const REFERENCE_DIR = 'references';

/**
 * Fixed order of recipe groups.
 *
 * Recipe files live under `references/recipes/<group>/`, and grouping them in
 * this order keeps the tree stable even when recipes are added or removed.
 */
export const RECIPE_GROUP_ORDER = [
  'forms',
  'data',
  'navigation',
  'modals',
  'layout',
  'state',
  'accessibility',
] as const;

/** A single generated file, with a POSIX-style path relative to the skill root. */
export interface SkillFile {
  /** Relative destination path, for example `references/components/button.md`. */
  path: string;

  /** Complete UTF-8 file content, ending with the generated marker. */
  content: string;
}

/**
 * Render-time identifiers recorded in the provenance section.
 *
 * These values are not part of the schema, so they are threaded in explicitly:
 * the skill version comes from `package.json`, the generator version from this
 * codebase, and the schema hash from the manifest. Keeping them out of the
 * schema preserves the determinism promise — identical inputs, identical
 * bytes — because none of them is a wall-clock value.
 */
export interface SkillRenderContext {
  /** Published version of the fluentui-skill package (from package.json). */
  skillVersion: string;

  /** Version of the generator that produced the tree. */
  generatorVersion: string;

  /** SHA-256 of the input schema, as recorded in the manifest. */
  schemaHash: string;
}

/**
 * Safe id pattern: lowercase kebab-case.
 *
 * Ids become file and directory names, so the pattern permits only `a-z`, `0-9`,
 * and single hyphens. It cannot express `..`, `/`, or a drive/absolute prefix,
 * which closes the path-traversal risk at the source.
 */
const SAFE_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/**
 * True when an id is safe to use as a single path component.
 *
 * @param id - Candidate id.
 * @returns True for a non-empty lowercase kebab-case id.
 */
export function isSafeSkillId(id: string): boolean {
  return typeof id === 'string' && SAFE_ID_PATTERN.test(id);
}

/** Throw a descriptive error when an id is not path-safe. */
function assertSafeId(kind: string, id: string): void {
  if (!isSafeSkillId(id)) {
    throw new Error(
      `Unsafe ${kind} id "${id}": ids must be lowercase kebab-case and may not contain "/" or "..".`,
    );
  }
}

/** Normalize line endings and append the generated marker. */
function finalize(markdown: string): string {
  const normalized = markdown.replace(/\r\n?/g, '\n').trimEnd();
  return appendMarker(normalized, GENERATED_MARKER);
}

/**
 * Drop a leading level-1 heading from authored content.
 *
 * Guide and recipe prose often starts with its own `# Title`. The renderer
 * adds a title from the schema, so keeping both would produce two H1s. Removing
 * the embedded one keeps a single document title and consistent metadata.
 */
function stripLeadingHeading(content: string): string {
  return content.replace(/^\s*#\s+[^\n]*\n+/, '').trim();
}

// ============================================================================
// Entity renderers
// ============================================================================

/**
 * Render the identity header of a component file: name, package, import,
 * category, stability, and a deprecation warning when applicable.
 */
function renderComponentHeader(component: ComponentEntry): string {
  const lines = [heading(1, component.name), ''];
  if (component.deprecated) {
    const message = component.deprecationMessage
      ? `: ${component.deprecationMessage}`
      : '';
    lines.push(`> ⚠️ **Deprecated**${message}`, '>');
  }
  const version = component.packageVersion ? ` v${component.packageVersion}` : '';
  lines.push(
    `> **Package**: \`${component.packageName}\`${version}`,
    `> **Import**: \`${component.importStatement}\``,
    `> **Category**: ${component.category}`,
    `> **Stability**: ${component.stability}`,
  );
  return lines.join('\n');
}

/** Render the overview prose, falling back to a neutral line for raw entries. */
function renderComponentOverview(component: ComponentEntry): string {
  const description = component.enhanced?.description?.trim();
  const whenToUse = component.enhanced?.whenToUse?.trim();
  const body =
    description && description !== ''
      ? description
      : `${component.name} is part of the \`${component.packageName}\` package.`;
  return joinSections([
    heading(2, 'Overview'),
    body,
    whenToUse ? `**When to use**: ${whenToUse}` : '',
  ]);
}

/** Render the Do's and Don'ts section from enhanced content. */
function renderBestPractices(component: ComponentEntry): string {
  const best = component.enhanced?.bestPractices;
  if (!best || (best.dos.length === 0 && best.donts.length === 0)) {
    return '';
  }
  return joinSections([
    heading(2, 'Best Practices'),
    best.dos.length > 0 ? joinSections([heading(3, "Do's"), bulletList(best.dos)]) : '',
    best.donts.length > 0 ? joinSections([heading(3, "Don'ts"), bulletList(best.donts)]) : '',
  ]);
}

/** Render anti-patterns: each mistake paired with its correct approach. */
function renderAntiPatterns(component: ComponentEntry): string {
  const items = component.enhanced?.antiPatterns;
  if (!items || items.length === 0) {
    return '';
  }
  const blocks = items.map((item) =>
    joinSections([
      heading(3, item.title),
      `❌ ${item.problem}`,
      `✅ ${item.solution}`,
    ]),
  );
  return joinSections([heading(2, 'Anti-Patterns'), ...blocks]);
}

/** Render accessibility guidance: requirements, keyboard table, ARIA, screen reader. */
function renderAccessibility(component: ComponentEntry): string {
  const a11y = component.enhanced?.accessibility;
  if (!a11y) {
    return '';
  }
  const keyboard =
    a11y.keyboardSupport.length > 0
      ? table(
          ['Key', 'Action'],
          a11y.keyboardSupport.map((entry) => [
            inlineCode(entry.key),
            escapeTableCell(entry.action),
          ]),
        )
      : '';
  return joinSections([
    heading(2, 'Accessibility'),
    a11y.requirements ? `**Requirements**: ${a11y.requirements.trim()}` : '',
    keyboard,
    a11y.ariaAttributes.length > 0
      ? `**ARIA**: ${a11y.ariaAttributes.join(', ')}`
      : '',
    a11y.screenReaderBehavior
      ? `**Screen Reader**: ${a11y.screenReaderBehavior.trim()}`
      : '',
  ]);
}

/** Render the links footer: the component's category and related recipes. */
function renderComponentLinks(
  component: ComponentEntry,
  categoryIds: ReadonlySet<string>,
  recipeGroups: ReadonlyMap<string, string>,
): string {
  const links: string[] = [];
  if (categoryIds.has(component.category)) {
    const label = escapeLinkLabel(`${component.category} category`);
    links.push(`[${label}](../categories/${component.category}.md)`);
  }
  for (const recipeId of component.enhanced?.relatedRecipes ?? []) {
    const group = recipeGroups.get(recipeId);
    if (group) {
      const label = escapeLinkLabel(`${recipeId} recipe`);
      links.push(`[${label}](../recipes/${group}/${recipeId}.md)`);
    }
  }
  if (component.relatedComponents.length > 0) {
    links.push(
      ...component.relatedComponents.map((name) =>
        name.replace(/\r?\n/g, ' ').trim(),
      ),
    );
  }
  if (links.length === 0) {
    return '';
  }
  return joinSections([heading(2, 'See Also'), bulletList(links)]);
}

/**
 * Render one component reference file from its scraped data and prose.
 *
 * Examples come only from story code; every other section is additive and is
 * omitted when its source field is missing.
 */
function renderComponentFile(
  component: ComponentEntry,
  categoryIds: ReadonlySet<string>,
  recipeGroups: ReadonlyMap<string, string>,
): string {
  return finalize(
    joinSections([
      renderComponentHeader(component),
      renderComponentOverview(component),
      renderPropsReference(component),
      renderExamplesSection(component),
      renderBestPractices(component),
      renderAntiPatterns(component),
      renderAccessibility(component),
      proseSection('Styling', component.enhanced?.stylingTips),
      proseSection('Performance', component.enhanced?.performanceNotes),
      proseSection('Theming & Tokens', component.enhanced?.themingNotes),
      proseSection('Migration Notes', component.enhanced?.migrationNotes),
      bulletSection('Edge Cases', component.enhanced?.edgeCases),
      renderComponentLinks(component, categoryIds, recipeGroups),
    ]),
  );
}

/** Render a foundation or quick-reference guide file. */
function renderGuideFile(guide: GuideEntry): string {
  const examples = guide.codeExamples
    .map((example) =>
      joinSections([
        heading(3, example.title),
        example.description?.trim() ?? '',
        fencedCode(example.code, example.language || 'tsx'),
      ]),
    );
  return finalize(
    joinSections([
      heading(1, guide.title),
      guide.category ? `> **Category**: ${guide.category}` : '',
      guide.content ? stripLeadingHeading(guide.content) : '',
      bulletSection('Key Takeaways', guide.keyTakeaways),
      examples.length > 0
        ? joinSections([heading(2, 'Examples'), ...examples])
        : '',
      bulletSection('Pitfalls', guide.pitfalls),
      proseSection('Accessibility', guide.accessibilityNotes),
      guide.referencedComponents.length > 0
        ? `**Referenced components**: ${guide.referencedComponents.join(', ')}`
        : '',
    ]),
  );
}

/** Render a category guidance file, including links to its components. */
function renderCategoryFile(
  category: CategoryGuidanceEntry,
  components: ReadonlyMap<string, ComponentEntry>,
): string {
  const componentLinks = category.componentIds
    .filter((id) => components.has(id))
    .map((id) => {
      const label = escapeLinkLabel(components.get(id)?.name ?? id);
      return `[${label}](../components/${id}.md)`;
    });
  return finalize(
    joinSections([
      heading(1, `${category.category} components`),
      heading(2, 'Overview'),
      category.overview,
      proseSection('When to Use', category.whenToUse),
      renderCategoryBestPractices(category),
      renderCategoryAntiPatterns(category),
      proseSection('Accessibility', category.accessibility),
      componentLinks.length > 0
        ? joinSections([
            heading(2, 'Components in this category'),
            bulletList(componentLinks),
          ])
        : '',
    ]),
  );
}

/** Render a category's shared Do's and Don'ts. */
function renderCategoryBestPractices(category: CategoryGuidanceEntry): string {
  const { dos, donts } = category.bestPractices;
  if (dos.length === 0 && donts.length === 0) {
    return '';
  }
  return joinSections([
    heading(2, 'Best Practices'),
    dos.length > 0 ? joinSections([heading(3, "Do's"), bulletList(dos)]) : '',
    donts.length > 0 ? joinSections([heading(3, "Don'ts"), bulletList(donts)]) : '',
  ]);
}

/** Render a category's shared anti-patterns. */
function renderCategoryAntiPatterns(category: CategoryGuidanceEntry): string {
  if (category.antiPatterns.length === 0) {
    return '';
  }
  const blocks = category.antiPatterns.map((item) =>
    joinSections([
      heading(3, item.title),
      `❌ ${item.problem}`,
      `✅ ${item.solution}`,
    ]),
  );
  return joinSections([heading(2, 'Anti-Patterns'), ...blocks]);
}

/** Render a recipe file from its prose, examples, and cross-links. */
function renderRecipeFile(
  recipe: RecipeEntry,
  components: ReadonlyMap<string, ComponentEntry>,
): string {
  // `components` is keyed by lowercased component name; recipes reference
  // components by display name rather than by id.
  const examples = recipe.examples
    .map((example) =>
      joinSections([
        heading(3, example.name),
        example.description?.trim() ?? '',
        fencedCode(example.code, example.language || 'tsx'),
      ]),
    );
  const componentLinks = recipe.referencedComponents
    .map((name) => components.get(name.trim().toLowerCase()))
    .filter((component): component is ComponentEntry => component !== undefined)
    .map((component) => {
      const label = escapeLinkLabel(component.name);
      return `[${label}](../../components/${component.id}.md)`;
    });
  return finalize(
    joinSections([
      heading(1, recipe.title),
      `> **Group**: ${recipe.group}`,
      proseSection('Goal', recipe.goal),
      proseSection('When to Use', recipe.whenToUse),
      proseSection('When Not to Use', recipe.whenNotToUse),
      recipe.content ? stripLeadingHeading(recipe.content) : '',
      examples.length > 0
        ? joinSections([heading(2, 'Examples'), ...examples])
        : '',
      bulletSection('Pitfalls', recipe.pitfalls),
      proseSection('Accessibility', recipe.accessibilityNotes),
      componentLinks.length > 0
        ? joinSections([
            heading(2, 'Components used'),
            bulletList(componentLinks),
          ])
        : '',
    ]),
  );
}

/**
 * Format the package versions that the scraped components come from as a
 * compact range and count.
 *
 * Counting is per package, not per component: many components share one package
 * (the Button family, for example), so counting entries would overstate how many
 * packages the snapshot covers. Only plain `x.y.z` versions are considered;
 * prerelease or malformed values are ignored so a single odd value cannot
 * distort the range. Comparison is numeric by major, then minor, then patch, so
 * `9.10.0` sorts above `9.2.0` rather than being compared as text.
 *
 * @param components - Component entries carrying `packageName`/`packageVersion`
 * @returns For example `2 packages, 9.2.0–9.10.0`, or undefined when none
 */
export function formatPackageVersionRange(
  components: readonly ComponentEntry[],
): string | undefined {
  // Map each package to one parsed version. Taking the first valid version per
  // package keeps the result deterministic for a given schema.
  const versionByPackage = new Map<string, number[]>();
  for (const component of components) {
    if (versionByPackage.has(component.packageName)) {
      continue;
    }
    const parsed = parsePlainVersion(component.packageVersion);
    if (parsed) {
      versionByPackage.set(component.packageName, parsed);
    }
  }

  const versions = [...versionByPackage.values()];
  if (versions.length === 0) {
    return undefined;
  }

  const sorted = [...versions].sort(compareVersions);
  const min = formatVersion(sorted[0]);
  const max = formatVersion(sorted[sorted.length - 1]);
  const noun = versions.length === 1 ? 'package' : 'packages';
  const range = min === max ? min : `${min}–${max}`;

  return `${versions.length} ${noun}, ${range}`;
}

/**
 * Parse a plain `x.y.z` version into its numeric parts.
 *
 * @param version - Candidate version string
 * @returns The three numeric parts, or undefined when not plain semver
 */
function parsePlainVersion(version: string): number[] | undefined {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(version);
  if (!match) {
    return undefined;
  }
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

/**
 * Compare two parsed versions by major, minor, then patch.
 *
 * @param a - First parsed version
 * @param b - Second parsed version
 * @returns A negative, zero, or positive number following `Array#sort` rules
 */
function compareVersions(a: number[], b: number[]): number {
  for (let index = 0; index < 3; index += 1) {
    const difference = a[index] - b[index];
    if (difference !== 0) {
      return difference;
    }
  }
  return 0;
}

/** Render a parsed version back to `x.y.z`. */
function formatVersion(parts: number[]): string {
  return parts.join('.');
}

/**
 * Render the "Source & versions" provenance section.
 *
 * The section lists the FluentUI source ref and commit, the umbrella package
 * version when present, the component package version range, and the skill,
 * generator, and schema identifiers. It deliberately excludes any timestamp so
 * generated references stay reproducible.
 *
 * Rows whose data is absent are omitted. The schema is validated before
 * rendering, so `sources.fluentui` is always present.
 *
 * @param schema - The enhanced schema
 * @param context - Skill version, generator version, and schema hash
 * @returns A Markdown section
 */
function renderProvenance(
  schema: FluentUISchema,
  context: SkillRenderContext,
): string {
  const source = schema.sources.fluentui;
  const rows: string[][] = [
    ['Fluent UI version', escapeTableCell(schema.version)],
    [
      'Fluent UI source',
      `${inlineCode(source.ref)} @ ${inlineCode(source.commit.slice(0, 7))}`,
    ],
  ];

  if (source.packageName && source.packageVersion) {
    rows.push([
      'Umbrella package',
      `${inlineCode(source.packageName)} ${escapeTableCell(source.packageVersion)}`,
    ]);
  }

  const range = formatPackageVersionRange(schema.components ?? []);
  if (range) {
    rows.push(['Component packages', escapeTableCell(range)]);
  }

  rows.push(
    ['Skill version', escapeTableCell(context.skillVersion)],
    ['Generator', escapeTableCell(context.generatorVersion)],
    ['Schema hash', inlineCode(context.schemaHash.slice(0, 12))],
  );

  return joinSections([
    heading(2, 'Source & versions'),
    table(['Item', 'Value'], rows),
  ]);
}

/** Render the routing index: task→recipe map, category index, and all references. */
function renderIndexFile(
  schema: FluentUISchema,
  orderedRecipes: readonly RecipeEntry[],
  orderedComponents: readonly ComponentEntry[],
  context: SkillRenderContext,
): string {
  const taskTable = table(
    ['Task', 'Recipe', 'Group'],
    orderedRecipes.map((recipe) => [
      escapeTableCell(recipe.title),
      `[${escapeLinkLabel(recipe.id)}](recipes/${recipe.group}/${recipe.id}.md)`,
      escapeTableCell(recipe.group),
    ]),
  );

  const categoryTable = table(
    ['Category', 'Components'],
    schema.categoryGuidance.map((category) => [
      `[${escapeLinkLabel(category.category)}](categories/${category.id}.md)`,
      String(category.componentIds.length),
    ]),
  );

  return finalize(
    joinSections([
      heading(1, 'FluentUI reference index'),
      'Hand-written routing lives in `SKILL.md`; this file indexes every generated reference.',
      renderProvenance(schema, context),
      heading(2, 'Task → recipe'),
      taskTable,
      heading(2, 'Categories'),
      categoryTable,
      heading(2, 'Foundation'),
      bulletList(
        schema.foundation.map(
          (guide) =>
            `[${escapeLinkLabel(guide.title)}](foundation/${guide.id}.md)`,
        ),
      ),
      heading(2, 'Components'),
      bulletList(
        orderedComponents.map(
          (component) =>
            `[${escapeLinkLabel(component.name)}](components/${component.id}.md)`,
        ),
      ),
      heading(2, 'Quick reference'),
      bulletList(
        schema.quickReference.map(
          (guide) =>
            `[${escapeLinkLabel(guide.title)}](quick-reference/${guide.id}.md)`,
        ),
      ),
    ]),
  );
}

// ============================================================================
// Mapping entry point
// ============================================================================

/**
 * Compare two strings by code unit.
 *
 * A locale-free comparison is used on purpose: `localeCompare` can order
 * differently depending on the host locale, which would break the promise that
 * the same schema always produces the same bytes.
 */
function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Compare two objects by their `id` field for deterministic ordering. */
function byId(a: { id: string }, b: { id: string }): number {
  return compareStrings(a.id, b.id);
}

/**
 * Turn an enhanced schema into the complete set of skill files.
 *
 * The function validates every id and recipe group first, then renders all
 * files in memory. It never writes to disk; a thrown error therefore guarantees
 * that no partial tree can appear.
 *
 * Order is deterministic and intentional: `index.md` first, then foundation,
 * components, and quick references ordered by id, then categories by id, then
 * recipes by fixed group order and id. The result is not re-sorted by path.
 *
 * @param schema - The enhanced schema to render.
 * @param context - Skill version, generator version, and schema hash.
 * @returns Every generated file, in mapping order.
 * @throws When an id is unsafe or a recipe group is unknown.
 */
export function buildSkillFiles(
  schema: FluentUISchema,
  context: SkillRenderContext,
): SkillFile[] {
  const components = [...(schema.components ?? [])].sort(byId);
  const foundation = [...(schema.foundation ?? [])].sort(byId);
  const categories = [...(schema.categoryGuidance ?? [])].sort(byId);
  const quickReference = [...(schema.quickReference ?? [])].sort(byId);
  const recipes = [...(schema.recipes ?? [])];

  for (const component of components) {
    assertSafeId('component', component.id);
    assertSafeId('category', component.category);
  }
  for (const guide of [...foundation, ...quickReference]) {
    assertSafeId('guide', guide.id);
  }
  for (const category of categories) {
    assertSafeId('category', category.id);
  }
  for (const recipe of recipes) {
    assertSafeId('recipe', recipe.id);
    if (!RECIPE_GROUP_ORDER.includes(recipe.group as (typeof RECIPE_GROUP_ORDER)[number])) {
      throw new Error(
        `Unknown recipe group "${recipe.group}" for recipe "${recipe.id}". Allowed groups: ${RECIPE_GROUP_ORDER.join(', ')}.`,
      );
    }
  }

  const orderedRecipes = [...recipes].sort(
    (a, b) =>
      RECIPE_GROUP_ORDER.indexOf(a.group as (typeof RECIPE_GROUP_ORDER)[number]) -
        RECIPE_GROUP_ORDER.indexOf(b.group as (typeof RECIPE_GROUP_ORDER)[number]) ||
      compareStrings(a.id, b.id),
  );

  const componentById = new Map(components.map((c) => [c.id, c]));
  const componentByName = new Map(
    components.map((c) => [c.name.toLowerCase(), c]),
  );
  const categoryIds = new Set(categories.map((c) => c.id));
  const recipeGroups = new Map(recipes.map((r) => [r.id, r.group]));

  const files: SkillFile[] = [
    {
      path: `${REFERENCE_DIR}/index.md`,
      content: renderIndexFile(schema, orderedRecipes, components, context),
    },
    ...foundation.map((guide) => ({
      path: `${REFERENCE_DIR}/foundation/${guide.id}.md`,
      content: renderGuideFile(guide),
    })),
    ...components.map((component) => ({
      path: `${REFERENCE_DIR}/components/${component.id}.md`,
      content: renderComponentFile(component, categoryIds, recipeGroups),
    })),
    ...categories.map((category) => ({
      path: `${REFERENCE_DIR}/categories/${category.id}.md`,
      content: renderCategoryFile(category, componentById),
    })),
    ...orderedRecipes.map((recipe) => ({
      path: `${REFERENCE_DIR}/recipes/${recipe.group}/${recipe.id}.md`,
      content: renderRecipeFile(recipe, componentByName),
    })),
    ...quickReference.map((guide) => ({
      path: `${REFERENCE_DIR}/quick-reference/${guide.id}.md`,
      content: renderGuideFile(guide),
    })),
  ];

  // Order is intentionally not re-sorted by path: each collection is already
  // deterministic (ids alphabetical), and recipes keep their fixed group order.
  return files;
}
